### ISSUE TITLE
BootCDN 存在投毒风险，建议更换其他 CDN 服务

### ISSUE THREAD

**Issue by shirok1** [hust-open-atom-club/linux-edu-rank#13]
https://blog.feizhuqwq.com/86

https://github.com/hust-open-atom-club/linux-edu-rank/blob/4b385c3fddf79d1480a38c429a7747a813e6e5f3/index.html#L9-L15

**Comment by mudongliang** [comment]
好的，多谢，我们已经安排同学来看这个issue了

**Comment by THINKER-ONLY** [comment]
Merge Reason:
As of now, the poisoning issue with BootCDN has not been resolved, and it is necessary to switch to a different CDN service to ensure the normal use of the website.
Using Zstatic.net in conjunction with SRI is an better choice, as it can ensure that the content is not tampered with.

**Comment by mudongliang** [comment]
You should comment on the PR instead of this issue.
