### ISSUE TITLE
Split function usage and definition

### ISSUE THREAD

**Issue by tttturtle-russ** [hust-open-atom-club/linux-edu-rank#20]
Currently the file contains both definitions and usage, which makes it hard to read and maintain.
However, I don't know if this is the Pythonic way.

**Comment by THINKER-ONLY** [comment]
I can have a try if there is more descriptions for this issue

**Comment by tttturtle-russ** [comment]
to be specific, touch two Python files, one includes function definition and implementation while the other calls these functions and executes the `main` function.

**Comment by THINKER-ONLY** [comment]
OK, plz assign this issue for me
